apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
  namespace: mlapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
        - name: model
          image: IMAGE_ECR_URI_MODEL   
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
