apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
  namespace: mlapp
spec:
  replicas: 1
  selector:
    matchLabels: { app: model }
  template:
    metadata:
      labels: { app: model }
    spec:
      tolerations:
        - key: "node.kubernetes.io/memory-pressure"
          operator: "Exists"
          effect: "NoSchedule"

      containers:
      - name: model
        image: IMAGE_ECR_URI_MODEL
        ports:
          - containerPort: 8000
        env:
          - name: ONNX_URL
            valueFrom:
              secretKeyRef:
                name: model-config
                key: ONNX_URL
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 100
          periodSeconds: 15
          timeoutSeconds: 2
          failureThreshold: 120
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 600Mi
