apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mlapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      tolerations:
        - key: "node.kubernetes.io/memory-pressure"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: backend
          image: IMAGE_ECR_URI_BACKEND
          imagePullPolicy: Always
          envFrom:
            - configMapRef: { name: app-config }
            - secretRef:    { name: app-secrets }
          ports:
            - containerPort: 8000
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          cpu: 200m
          memory: 300Mi
