apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mlapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      tolerations:
        - key: "node.kubernetes.io/memory-pressure"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: backend
          image: IMAGE_ECR_URI_BACKEND
          imagePullPolicy: Always
          envFrom:
            - configMapRef: { name: app-config }
            - secretRef:    { name: app-secrets }
          ports:
            - containerPort: 8000
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "300m", memory: "512Mi" }
