apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: mlapp
spec:
  serviceName: "mongodb-svc"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0
          args: ["--bind_ip_all"]
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom: { secretKeyRef: { name: app-secrets, key: MONGO_ROOT_USERNAME } }
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom: { secretKeyRef: { name: app-secrets, key: MONGO_ROOT_PASSWORD } }
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "300m", memory: "512Gi" }
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        #storageClassName: gp3   ----
        resources:
          requests:
            storage: 8Gi
