apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: mlapp
spec:
  clusterIP: None   
  # headless for stable DNS 
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
